### ISSUE TITLE
java.lang.Error: Unresolved compilation problem:  	VERSION_2_3_29 cannot be resolved or is not a field

### ISSUE THREAD

**Issue by chik145** [extent-framework/extentreports-java#110]
Facing This Issue With 4.1.0 Version
At This Line: reports.attachReporter(extentHtmlReporter);

**Comment by anshooarora** [comment]
@chik145 Please update to version `4.1.1`, this was fixed earlier this morning.

**Comment by chik145** [comment]
Thanks @anshooarora , Please add this version under maven repo.

**Comment by anshooarora** [comment]
Its available on Nexus:  https://search.maven.org/artifact/com.aventstack/extentreports/4.1.1/jar

**Comment by chik145** [comment]
@anshooarora  i have updated my POM with Extent Report 4.1.0 And extentreports-cucumber4-adapter 1.0.9 But This Issue Is Still There

java.lang.NoClassDefFoundError: gherkin/formatter/Reporter

Any Idea ?

**Comment by anshooarora** [comment]
Can you check with 1.0.10?  This version updates to Cucumber-4.7.4, is that what you are using?  Please share your pom.

**Comment by chik145** [comment]
@anshooarora Updated To 1.0.10 . But Still Same. This Is My Current POM

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>groupId</groupId>
    <artifactId>Compas_GO_UI</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <cucumber.version>4.7.4</cucumber.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-core</artifactId>
            <version>${cucumber.version}</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>3.141.59</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.6</version>
        </dependency>

        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>4.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <version>5.5.2</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports-cucumber4-adapter</artifactId>
            <version>1.0.10</version>
        </dependency>

        <dependency>
            <groupId>com.vimalselvam</groupId>
            <artifactId>cucumber-extentsreport</artifactId>
            <version>3.1.1</version>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>gherkin</artifactId>
            <version>5.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>4.1.1</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>4.1.1</version>
        </dependency>

        <dependency>
            <groupId>net.masterthought</groupId>
            <artifactId>cucumber-reporting</artifactId>
            <version>4.11.2</version>
        </dependency>

    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <testSourceDirectory>${basedir}/src/main/java/tests</testSourceDirectory>
                    <testClassesDirectory>${project.build.directory}/classes/</testClassesDirectory>
                    <includes>
                        <include>**/*Runner*.java</include>
                    </includes>
                    <parallel>all</parallel>
                    <useUnlimitedThreads>true</useUnlimitedThreads>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>

                </configuration>
            </plugin>
        </plugins>
    </build>
</project>

**Comment by anshooarora** [comment]
Please remove the below deps and try again:

```
<dependency>
        <groupId>com.aventstack</groupId>
        <artifactId>extentreports</artifactId>
        <version>4.1.1</version>
    </dependency>
    <dependency>
        <groupId>com.vimalselvam</groupId>
        <artifactId>cucumber-extentsreport</artifactId>
        <version>3.1.1</version>
    </dependency>
```

**Comment by chik145** [comment]
@anshooarora  i can't comment extent reports because that is our primary report for project & if i remove cucumber-extentsreport. i won't get these functions. then how can i implement cucumber extent report ?

Reporter.loadXMLConfig(new File("src/test/resources/extent-config.xml"));
        Reporter.setSystemInfo("user", System.getProperty("user.name"));
        Reporter.setSystemInfo("os", "Mac OSX");
        Reporter.setTestRunnerOutput("Sample test runner output message");

**Comment by anshooarora** [comment]
Those dependencies will clash with the Cucumber version you are using in relation with the adapter:

```
<dependency>
        <groupId>com.aventstack</groupId>
        <artifactId>extentreports-cucumber4-adapter</artifactId>
        <version>1.0.10</version>
</dependency>
```

To load config, use `extent.properties`.  See [here](https://github.com/extent-framework/extentreports-cucumber4-adapter/blob/master/config/extent.properties#L18).  To set system information, set via `ExtentService`.

**Comment by chik145** [comment]
can you please tell me how to load config xml ? i am not getting

**Comment by anshooarora** [comment]
This example should help:  https://github.com/foursyth/extentreports-cucumberN-example

**Comment by Rodriguitos** [comment]
Hi anshooarora:

Is there a way to add a timestamp in the output folder?

Something like in the extent.properties file: 

`extent.reporter.html.out=target/extent-reports/test-output/HtmlReport_${timestamp}/ExtentHtml.html`

Thanks in advance
